---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Producer
        Name: ProducerMSP
        ID: ProducerMSP
        MSPDir: crypto-config/peerOrganizations/producer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ProducerMSP.admin', 'ProducerMSP.peer', 'ProducerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ProducerMSP.admin', 'ProducerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ProducerMSP.admin')"

    - &Manufacturer
        Name: ManufacturerMSP
        ID: ManufacturerMSP
        MSPDir: crypto-config/peerOrganizations/manufacturer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.peer', 'ManufacturerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin', 'ManufacturerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ManufacturerMSP.admin')"
                
    - &Deliverer
        Name: DelivererMSP
        ID: DelivererMSP
        MSPDir: crypto-config/peerOrganizations/deliverer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DelivererMSP.admin', 'DelivererMSP.peer', 'DelivererMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DelivererMSP.admin', 'DelivererMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DelivererMSP.admin')"
                
    - &Retailer
        Name: RetailerMSP
        ID: RetailerMSP
        MSPDir: crypto-config/peerOrganizations/retailer.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('RetailerMSP.admin', 'RetailerMSP.peer', 'RetailerMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('RetailerMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    # Batch Timeout: The amount of time to wait before creating a batch.
    BatchTimeout: 0.1s

    # Batch Size: Controls the number of messages batched into a block.
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a
        # batch.
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch. If the "kafka" OrdererType is
        # selected, set 'message.max.bytes' and 'replica.fetch.max.bytes' on
        # the Kafka brokers to a value that is larger than this one.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed
        # for the serialized messages in a batch. A message larger than the
        # preferred max bytes will result in a batch larger than preferred max
        # bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Producer
                    - *Manufacturer
                    - *Deliverer
                    - *Retailer
    ChannelAll:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Producer
                - *Manufacturer
                - *Deliverer
                - *Retailer
            Capabilities:
                <<: *ApplicationCapabilities
